export const BUTTON_HOST: { [key: string]: string } = {
  class: 'btn',
  '[class.btn-danger]': 'color === \'danger\' && theme === \'\'',
  '[class.btn-dark]': 'color === \'dark\' && theme === \'\'',
  '[class.btn-info]': 'color === \'info\' && theme === \'\'',
  '[class.btn-lg]': 'size === \'lg\'',
  '[class.btn-light]': 'color === \'light\' && theme === \'\'',
  '[class.btn-md]': 'size === \'md\'',
  '[class.btn-outline-danger]': 'color === \'danger\' && theme === \'outline\'',
  '[class.btn-outline-dark]': 'color === \'dark\' && theme === \'outline\'',
  '[class.btn-outline-info]': 'color === \'info\' && theme === \'outline\'',
  '[class.btn-outline-light]': 'color === \'light\' && theme === \'outline\'',
  '[class.btn-outline-primary]': 'color === \'primary\' && theme === \'outline\'',
  '[class.btn-outline-secondary]': 'color === \'secondary\' && theme === \'outline\'',
  '[class.btn-outline-success]': 'color === \'success\' && theme === \'outline\'',
  '[class.btn-outline-warning]': 'color === \'warning\' && theme === \'outline\'',
  '[class.btn-primary]': 'color === \'primary\' && theme === \'\'',
  '[class.btn-secondary]': 'color === \'secondary\' && theme === \'\'',
  '[class.btn-sm]': 'size === \'sm\'',
  '[class.btn-success]': 'color === \'success\' && theme === \'\'',
  '[class.btn-warning]': 'color === \'warning\' && theme === \'\'',
};
